apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-react-full-stack
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-react-full-stack
                port:
                  number: 80
