apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: simple-flask-app-dev
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: simple-flask-app
      images:
        - alias: app
          imageName: nicus98/simple-flask-app
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^[0-9a-f]{7}$"
          manifestTargets:
            kustomize:
              name: nicus98/simple-flask-app
      writeBackConfig:
        method: git
        gitConfig:
          branch: main
