apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: simple-react-full-stack
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: simple-react-full-stack
      images:
        - alias: app
          imageName: nicus98/simple-react-full-stack
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^[0-9a-f]{7}$"
          manifestTargets:
            kustomize:
              name: nicus98/simple-react-full-stack
      writeBackConfig:
        method: git
        gitConfig:
          branch: main
